# Environment variables
# - HOST_NAME
# - USER_NAME
 
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-browsers
 
    steps:
      - checkout
 
      - add_ssh_keys:
          fingerprints:
            - "d2:ee:ce:6b:d7:35:eb:9b:e3:ca:41:8a:38:ab:f8:1c"
 
      - run:
          name: Start ssh-keyscan
          command: |
            ssh-keyscan ${HOST_NAME} >> ~/.ssh/known_hosts
 
      - deploy:
          name: Start master deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                rsync -av --delete --exclude='.git' --exclude='.circleci' ./ ${USER_NAME}@${HOST_NAME}:/home/webuser/service2
            fi

      - deploy:
          name: Start deploy static files
          command: |
            ssh ${USER_NAME}@${HOST_NAME}

      - deploy:
          name: Change Directry
          command: |
            cd service2/mysite
      
      - deploy:
          name: Deploy Static
          command: |
            python3 manage.py collectstatic